name: Android CI - Build APK  
  
on:  
  push:  
    branches: [ main, master, dev ]  
  pull_request:  
    branches: [ main, master, dev ]  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
      
    steps:  
    - name: 检出代码  
      uses: actions/checkout@v4  
        
    - name: 设置 JDK 17  
      uses: actions/setup-java@v4  
      with:  
        java-version: '17'  
        distribution: 'temurin'  
        cache: gradle  
          
    - name: 授予 gradlew 执行权限  
      run: chmod +x gradlew  
        
    - name: 构建 Debug APK  
      run: ./gradlew assembleDebug  
        
    - name: 构建 Release APK  
      run: ./gradlew assembleRelease  
        
    - name: 上传 Debug APK  
      uses: actions/upload-artifact@v4  
      with:  
        name: fcmfix-debug  
        path: app/build/outputs/apk/debug/*.apk  
        retention-days: 30  
          
    - name: 上传 Release APK  
      uses: actions/upload-artifact@v4  
      with:  
        name: fcmfix-release  
        path: app/build/outputs/apk/release/*.apk  
        retention-days: 30